"""Add image, video, and file attachment fields

Revision ID: 6f888ca06d88
Revises: 
Create Date: 2024-10-13 02:21:56.492622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f888ca06d88'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('video_link', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('file_attachment_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_column('file_attachment_url')
        batch_op.drop_column('video_link')
        batch_op.drop_column('image_url')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
